/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Onur (https://sketchfab.com/onurpearl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-robot-3454c84d6eff4a9dabbfadbfd1f56524
Title: Mini Robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material} position={[0, 402.922, -96.684]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.material} position={[0, 402.922, -96.684]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Robot_Mat} position={[138.7, 277.325, 0]} rotation={[-Math.PI / 2, -0.093, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Robot_Mat} position={[0, 591.54, 6.318]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Robot_Mat} position={[139.816, 602.251, -3.373]} rotation={[-2.443, Math.PI / 2, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Robot_Mat} position={[0, 571.212, 20.865]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Robot_Mat} position={[0, 591.54, 6.318]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Robot_Mat} position={[0, 305.669, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Robot_Mat} position={[134.604, 305.583, 0.376]} rotation={[-1.703, -0.089, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Robot_Mat} position={[40.552, 253.96, 0]} rotation={[-Math.PI / 2, -0.367, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Robot_Mat} position={[136.471, 167.599, 18.685]} rotation={[-1.703, -0.004, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Robot_Mat} position={[140.071, 186.381, 16.193]} rotation={[-1.703, -0.004, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Robot_Mat} position={[91.348, 432.15, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Robot_Mat} position={[0, 289.063, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Robot_Mat} position={[143.822, 603.805, -5.224]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.Robot_Mat} position={[130.341, 603.805, -5.224]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Robot_Mat} position={[74.031, 426.068, -0.013]} rotation={[-Math.PI / 2, 1.407, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.Robot_Mat} position={[136.632, 282.51, 3.438]} rotation={[-1.703, -0.004, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Robot_Mat} position={[0, 331.625, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Robot_Mat} position={[47.881, 244.873, 0]} rotation={[-Math.PI / 2, -0.064, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Robot_Mat} position={[0, 482.302, -1.883]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Robot_Mat} position={[138.7, 277.325, 0]} rotation={[-Math.PI / 2, -0.093, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Robot_Mat} position={[49.494, 124.163, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.Robot_Mat} position={[106.316, 404.439, 0]} rotation={[-Math.PI / 2, -0.093, 0]} scale={100} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Robot_Mat} position={[0, 412.832, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
