/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Teacher.gltf 
Author: 3DWorkbench (https://sketchfab.com/3DWorkbench)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/army-robot-300fb02b18e94108b0f19edc2c2a3c82
Title: Army robot
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Teacher(props) {
  const { nodes, materials } = useGLTF('/Teacher.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[146.806, 616.981, -19.854]}>
          <group position={[102.777, 20.45, 41.946]} rotation={[Math.PI, 0, 0.02]}>
            <group position={[114.401, 61.459, 41.006]} rotation={[-1.619, -0.85, -2.957]}>
              <group position={[-54.24, -1.569, 12.95]} rotation={[1.538, -0.221, -2.344]}>
                <group position={[17.314, -63.623, 21.537]} rotation={[-2.128, -0.685, 1.101]}>
                  <group position={[-30.989, -0.153, -21.167]} rotation={[2.332, Math.PI / 2, 0]}>
                    <group position={[-31.322, 3.242, 31.541]} rotation={[1.571, 0.904, 3.122]}>
                      <mesh geometry={nodes.kmr_oneTex_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} />
                      <mesh geometry={nodes.f001_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[31.746, 53.626, 30.966]} rotation={[1.571, 0.404, -1.572]} />
                      <mesh geometry={nodes.f002_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, 27.176, 21.485]} rotation={[0, 1.418, -Math.PI]} />
                      <mesh geometry={nodes.f003_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, -3.045, 21.491]} rotation={[0, 1.418, -Math.PI]} />
                      <mesh geometry={nodes.f004_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, -32.705, 21.496]} rotation={[0, 1.418, -Math.PI]} />
                    </group>
                    <mesh geometry={nodes.mh_rotate__hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                  </group>
                  <mesh geometry={nodes.pr_rotate__hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                </group>
                <mesh geometry={nodes.midR_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
              </group>
              <mesh geometry={nodes.midL_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
            </group>
            <mesh geometry={nodes.midH_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
          </group>
          <mesh geometry={nodes.LH2texBBuvR_1_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
        </group>
        <group position={[-146.806, 616.981, -19.854]}>
          <group position={[-102.777, 20.45, 41.946]} rotation={[Math.PI, 0, 0.02]}>
            <group position={[-111.912, 65.882, 41.006]} rotation={[-1.621, 0.889, -2.957]}>
              <group position={[50.078, -20.897, 12.95]} rotation={[1.539, -0.145, 2.202]}>
                <group position={[-8.884, -65.335, 21.537]} rotation={[-2.08, 0.572, 1.104]}>
                  <group position={[-20.465, -23.27, -21.167]} rotation={[-Math.PI / 2, 0.716, 2.555]}>
                    <group position={[31.41, -2.233, 31.541]} rotation={[1.571, -1.079, -2.009]}>
                      <mesh geometry={nodes.kmr_oneTex_2_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} />
                      <mesh geometry={nodes.f001_2_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[34.079, 52.175, 30.966]} rotation={[1.577, -1.517, 0.734]} />
                      <mesh geometry={nodes.f002_2_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-16.809, 95.624, 21.485]} rotation={[-1.4, -0.452, 2.369]} />
                      <mesh geometry={nodes.f003_2_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-43.919, 82.27, 21.491]} rotation={[-1.4, -0.452, 2.369]} />
                      <mesh geometry={nodes.f004_2_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-70.526, 69.163, 21.496]} rotation={[-1.4, -0.452, 2.369]} />
                    </group>
                    <mesh geometry={nodes.mh_rotate__2_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                  </group>
                  <mesh geometry={nodes.pr_rotate__2_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                </group>
                <mesh geometry={nodes.midR_2_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
              </group>
              <mesh geometry={nodes.midL_2_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
            </group>
            <mesh geometry={nodes.midH_2_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
          </group>
          <mesh geometry={nodes.RH2texBBuvR_1_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
        </group>
        <group position={[10.894, 339.987, -0.387]}>
          <group position={[104.677, 1.425, 56.116]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[0.112, -182.755, 58.902]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[52.776, -18.163, 0.078]} rotation={[1.963, -Math.PI / 2, 0]}>
                <group position={[177.409, 62.858, 51.775]} rotation={[-Math.PI / 2, -Math.PI / 8, Math.PI / 2]}>
                  <mesh geometry={nodes.legHeight2_legbbSa_0.geometry} material={materials.legbbSa} />
                  <mesh geometry={nodes.legEnd_rotate_legbbSa_0.geometry} material={materials.legbbSa} position={[28.421, -90.242, -11.85]} rotation={[0, -Math.PI / 2, 0]} />
                </group>
                <mesh geometry={nodes.leg_rotate3_legbbSa_0.geometry} material={materials.legbbSa} />
              </group>
              <mesh geometry={nodes.legHeight1_legbbSa_0.geometry} material={materials.legbbSa} />
            </group>
            <mesh geometry={nodes.leg_rotate2_legbbSa_0.geometry} material={materials.legbbSa} />
          </group>
          <mesh geometry={nodes.LlegBase_rotateR_1_legbbSa_0.geometry} material={materials.legbbSa} />
        </group>
        <group position={[-10.894, 339.987, -0.387]}>
          <group position={[-104.677, 1.425, 56.116]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[-0.112, -182.755, 58.902]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[-52.776, -18.163, 0.078]} rotation={[-1.178, Math.PI / 2, 0]}>
                <group position={[177.409, -62.858, 51.775]} rotation={[Math.PI / 2, -Math.PI / 8, Math.PI / 2]}>
                  <mesh geometry={nodes.legHeight2_2_legbbSa_0.geometry} material={materials.legbbSa} />
                  <mesh geometry={nodes.legEnd_rotate_2_legbbSa_0.geometry} material={materials.legbbSa} position={[-28.421, -90.242, -11.85]} rotation={[-Math.PI, Math.PI / 2, 0]} />
                </group>
                <mesh geometry={nodes.leg_rotate3_2_legbbSa_0.geometry} material={materials.legbbSa} />
              </group>
              <mesh geometry={nodes.legHeight1_2_legbbSa_0.geometry} material={materials.legbbSa} />
            </group>
            <mesh geometry={nodes.leg_rotate2_2_legbbSa_0.geometry} material={materials.legbbSa} />
          </group>
          <mesh geometry={nodes.RlegBase_rotateR_1_legbbSa_0.geometry} material={materials.legbbSa} />
        </group>
        <group position={[146.806, 616.981, -19.854]}>
          <group position={[102.777, 20.45, 41.946]} rotation={[Math.PI, 0, 0.02]}>
            <group position={[114.401, 61.459, 41.006]} rotation={[-1.619, -0.85, -2.957]}>
              <group position={[-54.24, -1.569, 12.95]} rotation={[1.538, -0.221, -2.344]}>
                <group position={[17.314, -63.623, 21.537]} rotation={[-2.128, -0.685, 1.101]}>
                  <group position={[-30.989, -0.153, -21.167]} rotation={[2.332, Math.PI / 2, 0]}>
                    <group position={[-31.322, 3.242, 31.541]} rotation={[1.571, 0.904, 3.122]}>
                      <mesh geometry={nodes.kmr_oneTex_3_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} />
                      <mesh geometry={nodes.f001_3_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[31.746, 53.626, 30.966]} rotation={[1.571, 0.404, -1.572]} />
                      <mesh geometry={nodes.f002_3_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, 27.176, 21.485]} rotation={[0, 1.418, -Math.PI]} />
                      <mesh geometry={nodes.f003_3_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, -3.045, 21.491]} rotation={[0, 1.418, -Math.PI]} />
                      <mesh geometry={nodes.f004_3_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[93.209, -32.705, 21.496]} rotation={[0, 1.418, -Math.PI]} />
                    </group>
                    <mesh geometry={nodes.mh_rotate__3_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                  </group>
                  <mesh geometry={nodes.pr_rotate__3_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                </group>
                <mesh geometry={nodes.midR_3_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
              </group>
              <mesh geometry={nodes.midL_3_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
            </group>
            <mesh geometry={nodes.midH_3_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
          </group>
          <mesh geometry={nodes.LH2texBBuvR_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
        </group>
        <group position={[-146.806, 616.981, -19.854]}>
          <group position={[-102.777, 20.45, 41.946]} rotation={[Math.PI, 0, 0.02]}>
            <group position={[-111.912, 65.882, 41.006]} rotation={[-1.621, 0.889, -2.957]}>
              <group position={[50.078, -20.897, 12.95]} rotation={[1.539, -0.145, 2.202]}>
                <group position={[-8.884, -65.335, 21.537]} rotation={[-2.08, 0.572, 1.104]}>
                  <group position={[-20.465, -23.27, -21.167]} rotation={[-Math.PI / 2, 0.716, 2.555]}>
                    <group position={[31.41, -2.233, 31.541]} rotation={[1.571, -1.079, -2.009]}>
                      <mesh geometry={nodes.kmr_oneTex_4_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} />
                      <mesh geometry={nodes.f001_4_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[34.079, 52.175, 30.966]} rotation={[1.577, -1.517, 0.734]} />
                      <mesh geometry={nodes.f002_4_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-16.809, 95.624, 21.485]} rotation={[-1.4, -0.452, 2.369]} />
                      <mesh geometry={nodes.f003_4_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-43.919, 82.27, 21.491]} rotation={[-1.4, -0.452, 2.369]} />
                      <mesh geometry={nodes.f004_4_hbbp2Sa_0.geometry} material={materials.hbbp2Sa} position={[-70.526, 69.163, 21.496]} rotation={[-1.4, -0.452, 2.369]} />
                    </group>
                    <mesh geometry={nodes.mh_rotate__4_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                  </group>
                  <mesh geometry={nodes.pr_rotate__4_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
                </group>
                <mesh geometry={nodes.midR_4_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
              </group>
              <mesh geometry={nodes.midL_4_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
            </group>
            <mesh geometry={nodes.midH_4_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
          </group>
          <mesh geometry={nodes.RH2texBBuvR_hbbp1Sa_0.geometry} material={materials.hbbp1Sa} />
        </group>
        <group position={[10.894, 339.987, -0.387]}>
          <group position={[104.677, 1.425, 56.116]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[0.112, -182.755, 58.902]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[52.776, -18.163, 0.078]} rotation={[1.963, -Math.PI / 2, 0]}>
                <group position={[177.409, 62.858, 51.775]} rotation={[-Math.PI / 2, -Math.PI / 8, Math.PI / 2]}>
                  <mesh geometry={nodes.legHeight2_3_legbbSa_0.geometry} material={materials.legbbSa} />
                  <mesh geometry={nodes.legEnd_rotate_3_legbbSa_0.geometry} material={materials.legbbSa} position={[28.421, -90.242, -11.85]} rotation={[0, -Math.PI / 2, 0]} />
                </group>
                <mesh geometry={nodes.leg_rotate3_3_legbbSa_0.geometry} material={materials.legbbSa} />
              </group>
              <mesh geometry={nodes.legHeight1_3_legbbSa_0.geometry} material={materials.legbbSa} />
            </group>
            <mesh geometry={nodes.leg_rotate2_3_legbbSa_0.geometry} material={materials.legbbSa} />
          </group>
          <mesh geometry={nodes.LlegBase_rotateR_legbbSa_0.geometry} material={materials.legbbSa} />
        </group>
        <group position={[-10.894, 339.987, -0.387]}>
          <group position={[-104.677, 1.425, 56.116]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[-0.112, -182.755, 58.902]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[-52.776, -18.163, 0.078]} rotation={[-1.178, Math.PI / 2, 0]}>
                <group position={[177.409, -62.858, 51.775]} rotation={[Math.PI / 2, -Math.PI / 8, Math.PI / 2]}>
                  <mesh geometry={nodes.legHeight2_4_legbbSa_0.geometry} material={materials.legbbSa} />
                  <mesh geometry={nodes.legEnd_rotate_4_legbbSa_0.geometry} material={materials.legbbSa} position={[-28.421, -90.242, -11.85]} rotation={[-Math.PI, Math.PI / 2, 0]} />
                </group>
                <mesh geometry={nodes.leg_rotate3_4_legbbSa_0.geometry} material={materials.legbbSa} />
              </group>
              <mesh geometry={nodes.legHeight1_4_legbbSa_0.geometry} material={materials.legbbSa} />
            </group>
            <mesh geometry={nodes.leg_rotate2_4_legbbSa_0.geometry} material={materials.legbbSa} />
          </group>
          <mesh geometry={nodes.RlegBase_rotateR_legbbSa_0.geometry} material={materials.legbbSa} />
        </group>
        <mesh geometry={nodes.head_Ind_1_head_Ind_0.geometry} material={materials.head_Ind} position={[-0.35, 707.236, 29.924]} />
        <mesh geometry={nodes.BASE_body_1_allBBbody_0.geometry} material={materials.allBBbody} position={[-11.18, 363.272, -2.457]} />
        <mesh geometry={nodes.head_Ind_head_Ind_0.geometry} material={materials.head_Ind} position={[-0.35, 707.236, 29.924]} />
        <mesh geometry={nodes.BASE_body_allBBbody_0.geometry} material={materials.allBBbody} position={[-11.18, 363.272, -2.457]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Teacher.gltf')
